# Generated by Django 3.0.3 on 2020-02-15 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('t_contact', models.CharField(blank=True, max_length=10, null=True)),
                ('languages', models.CharField(max_length=30)),
                ('locations', models.CharField(blank=True, max_length=40, null=True)),
                ('interest_rate', models.IntegerField(blank=True, null=True)),
                ('cultures', models.BooleanField(blank=True, default=False, null=True)),
                ('tuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
