# Generated by Django 3.0.3 on 2020-02-15 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('g_contact', models.CharField(max_length=10)),
                ('date_of_join', models.DateTimeField(blank=True, null=True)),
                ('tiers', models.IntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(blank=True, default=False, null=True)),
                ('base_rate', models.CharField(blank=True, default='3000', max_length=6, null=True)),
                ('verified', models.BooleanField(blank=True, default=False, null=True)),
                ('operating_level', models.CharField(default='state', max_length=10)),
                ('location', models.CharField(blank=True, max_length=40, null=True)),
                ('known_languages', models.CharField(max_length=30)),
                ('reviews', models.TextField(blank=True, max_length=350, null=True)),
                ('ratings', models.IntegerField(default=True, null=True)),
                ('cuisines', models.TextField(blank=True, default='kerala cuisines', max_length=40, null=True)),
                ('arts', models.TextField(blank=True, default='kerala arts', max_length=40, null=True)),
                ('hotspots', models.TextField(blank=True, default='kerala hotspots', max_length=40, null=True)),
                ('culture', models.TextField(blank=True, default='kerala culture', max_length=30, null=True)),
                ('guser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
